### ISSUE TITLE
Towards D5.1

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#19]
The following subtasks must be completed at indicated dates in order to make D5.1

- [x] Draft openPMD extension for MD data: Sept. 20 (Juncheng) -> #18 
- [x] Draft openPMD extension for Wavefront data: Oct. 21 (Carsten) -> #16
- [x] Draft openPMD extension for Raytracing (neutrons) data: Oct. 25 (Mads) -> #15 
- [x] Draft openPMD extension for Raytracing (photons) data: Oct. 21 (Aljosa) -> #15 
- [x] Draft report to Jordi: Oct. 30 (Carsten, Juncheng)
- [x] Final report D5.1 submitted: Nov. 31(Jordi, Carsten)
